apiVersion: v1
kind: Service
metadata:
  name: my-service-svc
  namespace: "new-ns"
  labels:
    app: "my-service"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8001
  selector:
    app: "my-service"
  type: "ClusterIP"
